# Reference data for the Bioscan Stats tab's "found / total" progress
# display. Sourced from the EDMC-BioScan / EDMC-ExploData plugins'
# open-source reference data (github.com/Silarn/EDMC-BioScan,
# github.com/Silarn/EDMC-ExploData), which in turn cite the Deep Space
# Network, the Codex NSP/Bio requirements spreadsheet, and the Canonn
# Biosheet as their sources. Current as of the data snapshot taken when this
# was written -- Frontier does occasionally add new species (e.g. Radicoida
# was added in 2026), so this may drift slightly out of date over time.

# Total number of known species per genus.
GENUS_SPECIES_TOTALS = {
    "Aleoida": 5,
    "Amphora Plant": 1,
    "Anemone": 8,
    "Bacterium": 13,
    "Bark Mound": 1,
    "Brain Tree": 8,
    "Cactoida": 5,
    "Clypeus": 3,
    "Concha": 4,
    "Crystalline Shards": 1,
    "Electricae": 2,
    "Fonticulua": 6,
    "Frutexa": 7,
    "Fumerola": 4,
    "Fungoida": 4,
    "Osseus": 6,
    "Radicoida": 1,
    "Recepta": 3,
    "Sinuous Tubers": 8,
    "Stratum": 8,
    "Tubus": 5,
    "Tussock": 15,
}

# Total number of known color variants per species. 0 means that species has
# no color variants (the species name itself is the only "look" it has --
# true for Anemone, Brain Tree, Sinuous Tubers, and a few singletons).
# NOTE: the source data contains both "Stratum Aranaemus" (1) and
# "Stratum Araneamus" (3) -- likely a naming inconsistency upstream. Both are
# kept as-is rather than guessing which is correct.
SPECIES_VARIANT_TOTALS = {
    "Bark Mound": 0,
    "Amphora Plant": 0,
    "Radicoida Unicus": 0,
    "Aleoida Arcus": 12,
    "Aleoida Coronamus": 12,
    "Aleoida Gravis": 12,
    "Aleoida Laminiae": 12,
    "Aleoida Spica": 12,
    "Blatteum Bioluminescent Anemone": 0,
    "Croceum Anemone": 0,
    "Luteolum Anemone": 0,
    "Prasinum Bioluminescent Anemone": 0,
    "Puniceum Anemone": 0,
    "Roseum Anemone": 0,
    "Roseum Bioluminescent Anemone": 0,
    "Rubeum Bioluminescent Anemone": 0,
    "Bacterium Acies": 6,
    "Bacterium Alcyoneum": 15,
    "Bacterium Aurasus": 15,
    "Bacterium Bullaris": 6,
    "Bacterium Cerbrus": 15,
    "Bacterium Informem": 6,
    "Bacterium Nebulus": 6,
    "Bacterium Omentum": 6,
    "Bacterium Scopulum": 6,
    "Bacterium Tela": 6,
    "Bacterium Verrata": 6,
    "Bacterium Vesicula": 6,
    "Bacterium Volu": 6,
    "Aureum Brain Tree": 0,
    "Gypseeum Brain Tree": 0,
    "Lindigoticum Brain Tree": 0,
    "Lividum Brain Tree": 0,
    "Ostrinum Brain Tree": 0,
    "Puniceum Brain Tree": 0,
    "Roseum Brain Tree": 0,
    "Viride Brain Tree": 0,
    "Cactoida Cortexum": 12,
    "Cactoida Lapis": 12,
    "Cactoida Peperatis": 12,
    "Cactoida Pullulanta": 12,
    "Cactoida Vermis": 12,
    "Clypeus Lacrimam": 10,
    "Clypeus Margaritus": 10,
    "Clypeus Speculumi": 10,
    "Concha Aureolas": 10,
    "Concha Biconcavis": 6,
    "Concha Labiata": 10,
    "Concha Renibus": 6,
    "Electricae Pluma": 6,
    "Electricae Radialem": 6,
    "Fonticulua Campestris": 15,
    "Fonticulua Digitos": 15,
    "Fonticulua Fluctus": 15,
    "Fonticulua Lapida": 15,
    "Fonticulua Segmentatus": 15,
    "Fonticulua Upupam": 15,
    "Frutexa Acus": 10,
    "Frutexa Collum": 10,
    "Frutexa Fera": 10,
    "Frutexa Flabellum": 10,
    "Frutexa Flammasis": 10,
    "Frutexa Metallicum": 10,
    "Frutexa Sponsae": 10,
    "Fumerola Aquatis": 6,
    "Fumerola Carbosis": 6,
    "Fumerola Extremus": 6,
    "Fumerola Nitris": 6,
    "Fungoida Bullarum": 6,
    "Fungoida Gelata": 6,
    "Fungoida Setisis": 6,
    "Fungoida Stabitis": 6,
    "Osseus Cornibus": 8,
    "Osseus Discus": 6,
    "Osseus Fractus": 8,
    "Osseus Pellebantus": 8,
    "Osseus Pumice": 6,
    "Osseus Spiralis": 8,
    "Recepta Conditivus": 6,
    "Recepta Deltahedronix": 6,
    "Recepta Umbrux": 13,
    "Crystalline Shards": 0,
    "Stratum Aranaemus": 1,
    "Stratum Araneamus": 3,
    "Stratum Cucumisis": 10,
    "Stratum Excutitus": 10,
    "Stratum Frigus": 10,
    "Stratum Laminamus": 10,
    "Stratum Limaxus": 10,
    "Stratum Paleas": 10,
    "Stratum Tectonicas": 10,
    "Albidum Sinuous Tubers": 0,
    "Blatteum Sinuous Tubers": 0,
    "Caeruleum Sinuous Tubers": 0,
    "Lindigoticum Sinuous Tubers": 0,
    "Prasinum Sinuous Tubers": 0,
    "Roseum Sinuous Tubers": 0,
    "Violaceum Sinuous Tubers": 0,
    "Viride Sinuous Tubers": 0,
    "Tubus Cavas": 13,
    "Tubus Compagibus": 13,
    "Tubus Conifer": 13,
    "Tubus Rosarium": 13,
    "Tubus Sororibus": 13,
    "Tussock Albata": 10,
    "Tussock Capillum": 10,
    "Tussock Caputus": 10,
    "Tussock Catena": 10,
    "Tussock Cultro": 10,
    "Tussock Divisa": 10,
    "Tussock Ignis": 10,
    "Tussock Pennata": 10,
    "Tussock Pennatis": 10,
    "Tussock Propagito": 10,
    "Tussock Serrati": 10,
    "Tussock Stigmasis": 10,
    "Tussock Triticum": 10,
    "Tussock Ventusa": 10,
    "Tussock Virgam": 10,
}

TOTAL_KNOWN_GENERA = len(GENUS_SPECIES_TOTALS)
TOTAL_KNOWN_SPECIES = sum(GENUS_SPECIES_TOTALS.values())
TOTAL_KNOWN_VARIANTS = sum(SPECIES_VARIANT_TOTALS.values())

# Genus -> total variants across all of that genus's species (sum of the
# relevant entries in SPECIES_VARIANT_TOTALS, computed directly from the
# same source data).
GENUS_VARIANT_TOTALS = {
    "Aleoida": 60,
    "Amphora Plant": 0,
    "Anemone": 0,
    "Bacterium": 105,
    "Bark Mound": 0,
    "Brain Tree": 0,
    "Cactoida": 60,
    "Clypeus": 30,
    "Concha": 32,
    "Crystalline Shards": 0,
    "Electricae": 12,
    "Fonticulua": 90,
    "Frutexa": 70,
    "Fumerola": 24,
    "Fungoida": 24,
    "Osseus": 44,
    "Radicoida": 0,
    "Recepta": 25,
    "Sinuous Tubers": 0,
    "Stratum": 73,
    "Tubus": 65,
    "Tussock": 150,
}
